# Generated by Django 5.0.2 on 2024-03-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=250)),
                ("name", models.CharField(max_length=250)),
                ("password", models.CharField(max_length=250)),
            ],
        ),
    ]
