# Generated by Django 5.0.2 on 2024-03-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Course_id", models.IntegerField()),
                ("name", models.CharField(max_length=250)),
                ("description", models.TextField()),
                ("illustration", models.CharField(max_length=250)),
                ("introduction", models.TextField()),
                ("image", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Design",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Design_id", models.IntegerField()),
                ("background", models.CharField(max_length=250)),
                ("target", models.CharField(max_length=250)),
                ("principle", models.CharField(max_length=250)),
            ],
        ),
    ]
