# Generated by Django 5.0.2 on 2024-03-16 02:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0003_course_design"),
    ]

    operations = [
        migrations.CreateModel(
            name="Statistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Statistics_id", models.IntegerField()),
                ("student", models.IntegerField()),
                ("rate", models.FloatField()),
                ("total_rate", models.FloatField()),
                ("rate_num", models.IntegerField()),
                ("qa", models.IntegerField()),
                ("resources", models.IntegerField()),
                ("homework", models.IntegerField()),
                ("announcement", models.IntegerField()),
                ("chapter", models.IntegerField()),
            ],
        ),
    ]
