# Generated by Django 5.0.2 on 2024-03-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0005_homeworka"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resources",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resource_id", models.IntegerField()),
                ("type", models.CharField(max_length=250)),
                ("name", models.CharField(max_length=250)),
                ("time", models.CharField(max_length=250)),
                ("size", models.CharField(max_length=250)),
                ("url", models.CharField(max_length=250)),
            ],
        ),
    ]
