# Generated by Django 5.0.2 on 2024-03-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0006_resources"),
    ]

    operations = [
        migrations.CreateModel(
            name="Qa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qa_id", models.IntegerField()),
                ("question", models.CharField(max_length=250)),
                ("answer", models.CharField(max_length=250)),
            ],
        ),
    ]
