# Generated by Django 5.0.2 on 2024-03-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0007_qa"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("announcement_id", models.IntegerField()),
                ("type", models.CharField(max_length=250)),
                ("content", models.CharField(max_length=250)),
                ("time", models.CharField(max_length=250)),
            ],
        ),
    ]
