# Generated by Django 5.0.2 on 2024-03-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0008_announcement"),
    ]

    operations = [
        migrations.CreateModel(
            name="Catalogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label_id", models.IntegerField()),
                ("label_intern_id", models.IntegerField()),
                ("label_fellow", models.CharField(max_length=250)),
            ],
        ),
    ]
