# Generated by Django 5.0.2 on 2024-03-16 11:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0012_kkk"),
    ]

    operations = [
        migrations.DeleteModel(
            name="nmsl",
        ),
    ]
