# Generated by Django 5.0.2 on 2024-03-17 02:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0013_delete_nmsl"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Course_id", models.IntegerField()),
                ("Design_id", models.IntegerField()),
                ("label_id", models.IntegerField()),
                ("announcement_id", models.IntegerField()),
                ("qa_id", models.IntegerField()),
                ("resource_id", models.IntegerField()),
                ("homework_id", models.IntegerField()),
                ("Statistics_id", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="kkk",
        ),
    ]
