# Generated by Django 5.0.2 on 2024-03-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0014_sum_delete_kkk"),
    ]

    operations = [
        migrations.CreateModel(
            name="Choose",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Student_id", models.IntegerField()),
                ("Lesson_id", models.IntegerField()),
                ("grade", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Lesson_name", models.CharField(max_length=250)),
                ("Lesson_id", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Professor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Teacher_id", models.IntegerField()),
                ("Lesson_id", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school", models.CharField(max_length=250)),
                ("Student_id", models.IntegerField()),
                ("password", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school", models.CharField(max_length=250)),
                ("Teacher_id", models.IntegerField()),
                ("password", models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
