# Generated by Django 5.0.2 on 2024-03-19 12:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0015_choose_lesson_professor_student_teacher_delete_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Student",
        ),
        migrations.DeleteModel(
            name="Teacher",
        ),
    ]
