# Generated by Django 5.0.2 on 2024-03-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0016_delete_student_delete_teacher"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Student_name", models.CharField(max_length=250)),
                ("Student_id", models.IntegerField()),
                ("password", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Teacher_name", models.CharField(max_length=250)),
                ("Teacher_id", models.IntegerField()),
                ("password", models.CharField(max_length=250)),
            ],
        ),
    ]
