# Generated by Django 5.0.2 on 2024-03-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0017_student_teacher"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("types", models.CharField(max_length=250)),
                ("title", models.CharField(max_length=250)),
                ("course", models.CharField(max_length=250)),
                ("startTime", models.CharField(max_length=250)),
                ("endTime", models.CharField(max_length=250)),
                ("announceTime", models.CharField(max_length=250)),
            ],
        ),
    ]
