# Generated by Django 5.0.6 on 2024-06-14 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sparkle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('illustration', models.CharField(max_length=250)),
                ('introduction', models.TextField()),
                ('image', models.CharField(max_length=255)),
            ],
        ),
    ]
