# Generated by Django 5.0.6 on 2024-06-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sparkle', '0003_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cid', models.IntegerField()),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('deadline', models.DateTimeField()),
                ('publish_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ChapterAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField()),
                ('chapter', models.IntegerField()),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('deadline', models.DateTimeField()),
                ('publish_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ChapterResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField()),
                ('chapter', models.IntegerField()),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('url', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='CourseChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField()),
                ('chapter', models.IntegerField()),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('aid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('cid', models.IntegerField()),
                ('grade', models.IntegerField()),
                ('rate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TeacherCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.IntegerField()),
                ('cid', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='background',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='principle',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='target',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
