# Generated by Django 5.0.6 on 2024-06-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sparkle', '0004_assignment_chapterassignment_chapterresource_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField()),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CourseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField()),
                ('type', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('deadline', models.DateTimeField()),
                ('publish_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CourseQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField()),
                ('tittle', models.CharField(max_length=250)),
                ('question', models.TextField()),
                ('sid', models.IntegerField()),
                ('name', models.CharField(max_length=250)),
                ('school', models.CharField(max_length=250)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.IntegerField()),
                ('answer', models.TextField()),
                ('sid', models.IntegerField()),
                ('name', models.CharField(max_length=250)),
                ('school', models.CharField(max_length=250)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
