# Generated by Django 5.0.6 on 2024-06-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sparkle', '0006_rename_qid_questionanswer_cid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField()),
                ('ccid', models.IntegerField()),
                ('chapter', models.IntegerField()),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
            ],
        ),
    ]
