# Generated by Django 5.0.6 on 2024-06-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sparkle', '0011_courseannouncement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseannouncement',
            name='time',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
