# Generated by Django 5.0.6 on 2024-06-16 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sparkle', '0014_chapterresource_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseassignment',
            name='time',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
