# Generated by Django 5.0.6 on 2024-06-16 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sparkle', '0015_courseassignment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourse',
            name='time',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
