# Generated by Django 5.0.6 on 2024-06-16 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sparkle', '0017_studentassignment_answer_studentassignment_response_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterKeyConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField()),
                ('ccid', models.IntegerField()),
                ('kid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ChapterProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField()),
                ('ccid', models.IntegerField()),
                ('pid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='KeyConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('importance', models.IntegerField()),
                ('difficulty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField()),
                ('title', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('difficulty', models.IntegerField()),
                ('importance', models.IntegerField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProblemKeyConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('kcid', models.IntegerField()),
            ],
        ),
    ]
