# Generated by Django 5.0.6 on 2024-06-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sparkle', '0019_studentproblem'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='holistic',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='innovation',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
