# Generated by Django 5.0.6 on 2024-06-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sparkle', '0021_studentacademyinfo_studentbasicinfo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEmotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('raw_image', models.TextField()),
                ('processed_image', models.TextField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=250)),
                ('gender_probability', models.FloatField()),
                ('emotion', models.CharField(max_length=250)),
                ('emotion_probability', models.FloatField()),
                ('left_eye_open', models.FloatField()),
                ('right_eye_open', models.FloatField()),
                ('time', models.CharField(max_length=250)),
            ],
        ),
    ]
