# Generated by Django 5.0.6 on 2024-06-15 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sparkle', '0007_childchapter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseannouncement',
            old_name='time',
            new_name='atime',
        ),
    ]
