# Generated by Django 5.0.6 on 2024-06-15 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sparkle', '0008_rename_time_courseannouncement_atime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='publish_time',
        ),
        migrations.RemoveField(
            model_name='chapterassignment',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='chapterassignment',
            name='publish_time',
        ),
        migrations.RemoveField(
            model_name='courseannouncement',
            name='atime',
        ),
        migrations.RemoveField(
            model_name='courseassignment',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='courseassignment',
            name='publish_time',
        ),
        migrations.RemoveField(
            model_name='coursequestion',
            name='time',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='time',
        ),
    ]
