# Generated by Django 5.0.6 on 2024-06-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sparkle', '0009_remove_assignment_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterresource',
            name='type',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
