# Generated by Django 5.0.6 on 2024-06-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sparkle', '0010_chapterresource_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseannouncement',
            name='type',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
