# Generated by Django 5.0.6 on 2024-06-16 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sparkle', '0013_chapterresource_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterresource',
            name='size',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
