# Generated by Django 5.0.6 on 2024-06-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sparkle', '0024_parent_studentactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('type', models.CharField(max_length=250)),
                ('score', models.IntegerField()),
            ],
        ),
    ]
